/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RawMaterialManagementRouteImport } from './routes/raw-material-management'
import { Route as ProductionSusgestionRouteImport } from './routes/production-susgestion'
import { Route as IndexRouteImport } from './routes/index'

const RawMaterialManagementRoute = RawMaterialManagementRouteImport.update({
  id: '/raw-material-management',
  path: '/raw-material-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionSusgestionRoute = ProductionSusgestionRouteImport.update({
  id: '/production-susgestion',
  path: '/production-susgestion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/production-susgestion': typeof ProductionSusgestionRoute
  '/raw-material-management': typeof RawMaterialManagementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/production-susgestion': typeof ProductionSusgestionRoute
  '/raw-material-management': typeof RawMaterialManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/production-susgestion': typeof ProductionSusgestionRoute
  '/raw-material-management': typeof RawMaterialManagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/production-susgestion' | '/raw-material-management'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/production-susgestion' | '/raw-material-management'
  id: '__root__' | '/' | '/production-susgestion' | '/raw-material-management'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductionSusgestionRoute: typeof ProductionSusgestionRoute
  RawMaterialManagementRoute: typeof RawMaterialManagementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/raw-material-management': {
      id: '/raw-material-management'
      path: '/raw-material-management'
      fullPath: '/raw-material-management'
      preLoaderRoute: typeof RawMaterialManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-susgestion': {
      id: '/production-susgestion'
      path: '/production-susgestion'
      fullPath: '/production-susgestion'
      preLoaderRoute: typeof ProductionSusgestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductionSusgestionRoute: ProductionSusgestionRoute,
  RawMaterialManagementRoute: RawMaterialManagementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
